`Restatement postponed: you need to ask more to better understand what restatement is and how to work with it`

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
restatement = pd.read_stata("../../data/CDP Cleaning/cleaned outputs/cdp_ghg_restatement.dta")

In [7]:
restatement

,id,scope,accounting_year,reporting_year,ghg1,ghg2_location,ghg2_market,ghg2,comment,ghg1_restatement,ghg1_change,ghg2loc_restatement,ghg2loc_change,ghg2mkt_restatement,ghg2mkt_change,ghg2_restatement,ghg2_change
0,44,1.0,2021.0,2022.0,167.800,NaN,NaN,NaN,N/A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44,1.0,2020.0,2021.0,117.700,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44,1.0,2020.0,2022.0,117.700,NaN,NaN,NaN,N/A,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
3,44,1.0,2019.0,2020.0,151.157,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44,1.0,2019.0,2022.0,150.500,NaN,NaN,NaN,N/A,1.0,-0.656998,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85193,895909,2.0,2021.0,2022.0,NaN,NaN,2233459.0,NaN,Worldwide 2021 emissions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85194,896044,1.0,2021.0,2022.0,963327.000,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85195,896044,2.0,2021.0,2022.0,NaN,NaN,1325626.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85196,896120,1.0,2021.0,2022.0,3308.000,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85197,896123,1.0,2021.0,2022.0,0.000,NaN,NaN,NaN,"Nil for ML, de minimis office space only for ML",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
restatement.isna().mean()

id                     0.000000
scope                  0.000000
accounting_year        0.000000
reporting_year         0.000000
ghg1                   0.486021
ghg2_location          0.663901
ghg2_market            0.809773
ghg2                   0.875983
comment                0.000000
ghg1_restatement       0.910350
ghg1_change            0.910350
ghg2loc_restatement    0.925597
ghg2loc_change         0.927416
ghg2mkt_restatement    0.958098
ghg2mkt_change         0.960727
ghg2_restatement       0.991995
ghg2_change            0.993497
dtype: float64

- Ideas: i can include indicator from this dataset on whether there has been a restatement or not. Would not go as far as including numerical predictor due to the large number of missing values.
- I will have to ask about this